name: Checks

on:
  workflow_dispatch: {}
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Dependencies
        run: npm ci

      # TODO(AB): ESLint dependencies are broken. Replace with a better and less complex linter.
      #      - name: Lint
      #        run: npm run lint:ci

      - name: Format
        run: npm run format:ci

      - name: Test
        run: npm test
