name: Deploy master into production on push
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: wrangler publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: prod
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
# TODO: Add organicmaps deploy.
